"""
Django settings for gestion project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import pymysql


pymysql.install_as_MySQLdb()
from datetime import timedelta





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cr+nt5y*e83_0+6&xopwjgvc9pi2ul&dys(q74o9uu=syp5q8h'

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = False  #mode  developpemnt

ALLOWED_HOSTS = ['*']


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3),  # Set to 30 days or any duration you prefer
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

#key maishapay

#MAISHAPAY_PUBLIC_KEY = "MP-SBPK-x0Gd7VV$LoktirHV$1Us1LWJnA6X/bDJ4doAby1RCILXolP$yDJ0DabYuR6qP$0DOL2mUX2ioQnH.oXpHN$XFat$/fkQPJ24FYhrGu1JE2mku.u02xfHEuVZ"
#MAISHAPAY_SECRET_KEY ="MP-SBPK-K23VdFI2f$soBERZE$Df4cpMyb0cnM0$$la1aO7aXk0We6I91AHfF6JayYcgAexrfQTf$rpUF84O.vBV$qeBzPv2vghTZiyy4MgPD8JBb7/20xC7m31qR4nu"

MAISHAPAY_PUBLIC_KEY ="MP-LIVEPK-Pn2EbCwCMCe7XoF1tEe4Un1tZsLH.OIXEN58mCQF00.1tD$Z1N9YRew2oyBHOHooI3ujk1$m0iF5njg$.g6bnnnX.u5RnwnzK6SMx$q$S2K60B$eL3SN0syy"
MAISHAPAY_SECRET_KEY ="MP-LIVEPK-JgSifRXoaSQ$JBy.HgtTXS0P02LU2trh164U7z2ahMhIPiuA19XW$HPsZpVYSNyF2Fb4JDzxnFxnuyvjdxcDu$$VuryIeu$kPBFeJLX20C$hvqlWGed0/gao"



#key pour sms avec africa's taiking
AFRICASTALKING_USERNAME = "sandbox"
AFRICASTALKING_API_KEY = "OroX4OpjX"


#reglage  gamil pour envoiyer le email
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'Myapp.email_backend.UnsafeEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'bilatechstore@gmail.com'
EMAIL_HOST_PASSWORD = 'rooy bjzh tzvn tosv'
DEFAULT_FROM_EMAIL = 'bilatechstore@gmail.com'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Myapp',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'corsheaders',
  
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


#if DEBUG:
   # INSTALLED_APPS += ['silk']
   # MIDDLEWARE = ['silk.middleware.SilkyMiddleware'] + MIDDLEWARE

CORS_ALLOWED_ORIGINS = [
            "http://localhost:5173",
            "https://bilasol.bilatech.org",
            "https://bilatech.vercel.app",
               # Adjust this to match your Vue.js app's URL
       ]


CORS_ALLOW_ALL_ORIGINS = True  #mode production 



CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://bilatech.vercel.app",
]


ROOT_URLCONF = 'gestion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'gestion.wsgi.application'




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,

    #  FIX ICI
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
    ],

    #  ordering par défaut CORRECT
    'DEFAULT_ORDERING': ['-created_at'],

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}









# Détecte si on est en production

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
        dsn="https://69c75d7cf34cd28b062600e1a029dcf3@o4510272353861632.ingest.us.sentry.io/4510273117421568",
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.5,        # surveille 50% des requêtes
        profiles_sample_rate=0.5,      # active le profilage
        send_default_pii=True,         # inclut les infos utilisateur (sûr si HTTPS)
        debug=False                     # ne pas afficher les logs Sentry en console
    )



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#  data base in django


'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gestionposdb',
        'USER': 'root',
        'PASSWORD':'BilaTech@25',
        'HOST': 'localhost',
        'PORT': '3306',
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}





if not DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }



if DEBUG:
    # DEV : sessions en base de données
    SESSION_ENGINE = "django.contrib.sessions.backends.db"
else:
    # PROD : sessions en cache (Redis)
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"







AUTHENTICATION_BACKENDS = [
    'Myapp.backends.CaseSensitiveModelBackend',  # ton backend sensible à la casse
]


AUTH_USER_MODEL = 'Myapp.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
MEDIA_URL ='/media/'
#MEDIA_ROOT = BASE_DIR / 'media' mode développement
MEDIA_ROOT = '/var/www/bilatech/media' # mode production

STATIC_URL = 'static/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
