# Generated by Django 5.1.4 on 2025-07-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='puchase_price',
            new_name='purchase_price',
        ),
    ]
