# Generated by Django 5.1.4 on 2025-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_rename_puchase_price_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
