# Generated by Django 5.1.4 on 2025-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_secretaccesskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency_preference',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', max_length=3),
        ),
    ]
