# Generated by Django 5.1.4 on 2025-03-14 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0006_subscripttion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscripttion",
            new_name="Subscription",
        ),
    ]
