# Generated by Django 5.1.4 on 2025-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0007_rename_subscripttion_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="adress",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="entrep_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="impot_number",
            field=models.CharField(default="0000000000", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rccm_number",
            field=models.CharField(default="0000000000", max_length=40),
            preserve_default=False,
        ),
    ]
