# Generated by Django 5.1.4 on 2025-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Myapp", "0010_cashout_cashoutdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashout",
            name="motif",
            field=models.CharField(default="Aucun motif", max_length=30),
            preserve_default=False,
        ),
    ]
