# Generated by Django 5.1.4 on 2025-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_depotproduct_exitdepot_exitdepotitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
