# Generated by Django 5.1.4 on 2025-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_invoice_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('valid', 'Valide'), ('canceled', 'Annuler')], default='valid', max_length=10),
        ),
    ]
