# Generated by Django 5.1.4 on 2025-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULER', 'Annuler')], default='VALIDE', max_length=10),
        ),
    ]
