# Generated by Django 5.1.4 on 2025-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tva',
            field=models.BooleanField(default=True),
        ),
    ]
