# Generated by Django 5.1.4 on 2025-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CAISSIER', 'Caissier'), ('GESTIONNAIRE_STOCK', 'Gestionnaire de stock')], default='ADMIN', max_length=30),
        ),
    ]
