# Generated by Django 5.1.4 on 2025-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('MEDIUM', 'Medium'), ('PREMIUM', 'Premium'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond')], default='BASIC', max_length=10),
        ),
    ]
