# Generated by Django 5.1.4 on 2025-11-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_alter_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='motif',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='status',
            field=models.CharField(choices=[('SORTIE', 'Sortie'), ('ENTRER', 'Entrer')], default='N/A', max_length=10),
        ),
    ]
