# Generated by Django 5.1.4 on 2025-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_customuser_deleted_at_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
