# Generated by Django 5.1.4 on 2025-12-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_customuser_permanent_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_nat',
            field=models.CharField(default='N/A', max_length=23, null=True),
        ),
    ]
