# Generated by Django 5.1.4 on 2025-12-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_userprofile_id_nat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entrynote',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
