# Generated by Django 5.1.4 on 2026-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=9, null=True),
        ),
    ]
