# Generated by Django 5.1.4 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='point_entry',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point_is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point_output',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
