# Generated by Django 5.1.4 on 2026-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0030_userprofile_point_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='points_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
