# Generated by Django 5.1.4 on 2026-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0031_invoice_points_discount_invoice_points_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_card_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
