# Generated by Django 5.1.4 on 2026-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0032_customer_loyalty_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_of_activity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='impot_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rccm_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
