# Generated by Django 5.1.4 on 2026-03-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0034_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
