# Generated by Django 5.1.4 on 2026-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0035_customuser_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='point_output',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
