# Generated by Django 5.1.4 on 2026-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0036_alter_userprofile_point_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashout',
            name='currency',
            field=models.CharField(blank=True, choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], max_length=5, null=True),
        ),
    ]
