# Generated by Django 5.1.4 on 2026-03-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0037_cashout_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrynote',
            name='currency',
            field=models.CharField(blank=True, choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], max_length=4, null=True),
        ),
    ]
