# Generated by Django 5.1.4 on 2026-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0038_entrynote_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
