# Generated by Django 5.1.4 on 2026-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0039_invoiceitem_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=2300, max_digits=10),
        ),
    ]
