# Generated by Django 5.1.4 on 2026-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0040_userprofile_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
