# Generated by Django 5.1.4 on 2026-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0042_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_free_frial',
            field=models.BooleanField(default=False),
        ),
    ]
