# Generated by Django 5.1.4 on 2026-03-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0044_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mount',
        ),
    ]
