# Generated by Django 5.1.4 on 2026-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0045_remove_payment_mount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('PAYMENT', 'Payment'), ('WITHDRAW', 'Withdraw')], max_length=20, null=True),
        ),
    ]
