# Generated by Django 5.1.4 on 2026-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0046_payment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_account_id',
            field=models.CharField(blank=True, max_length=50, null=tuple, unique=True),
            preserve_default=tuple,
        ),
    ]
