# Generated by Django 5.1.4 on 2026-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0048_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
