# Generated by Django 5.1.4 on 2026-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0049_customuser_is_online_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
