# Generated by Django 5.1.4 on 2026-04-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0052_connectionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionhistory',
            old_name='devise_info',
            new_name='device_info',
        ),
    ]
