# Generated by Django 5.1.4 on 2026-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0053_rename_devise_info_connectionhistory_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
