# Generated by Django 5.1.4 on 2026-04-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0054_connectionhistory_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionhistory',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
