# Generated by Django 5.1.4 on 2026-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0055_rename_ip_adress_connectionhistory_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
