# Generated by Django 5.1.4 on 2026-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0056_alter_connectionhistory_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
