# Generated by Django 5.1.4 on 2026-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0057_alter_connectionhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
