# Generated by Django 5.1.4 on 2026-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0058_alter_connectionhistory_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
